### ISSUE TITLE
Implement some sharing funtionality

### ISSUE THREAD

**Issue by headione** [criticalmaps/criticalmaps-ios#9] opened 2015-09-29 21:51 UTC
It would be nice to share the app to social media channels.

**Comment by mltbnz** [comment] 2019-04-13 09:41
Hey. What do you think should be shared from within the app? The app itself or some of its content?

**Comment by stephanlindauer** [comment] 2019-04-15 13:29
lowest hanging fruit imho would be a static thing that points people to the website. we could then improve from there.

**Comment by mltbnz** [comment] 2019-04-17 07:05
Alright. Sounds good. Maybe put it in the settings?

**Comment by stephanlindauer** [comment] 2019-04-17 09:13
in android we have a tab called "about" in which you will find stuff like that:
![Screenshot_20190417-111051](https://user-images.githubusercontent.com/1323145/56275800-b28da680-6101-11e9-9ff5-61b98854389a.png)
![Screenshot_20190417-111045](https://user-images.githubusercontent.com/1323145/56275820-ba4d4b00-6101-11e9-9aae-23bfc07edf3d.png)

**Comment by zutrinken** [comment] 2019-04-17 10:30
@stephanlindauer regular links to our website and profile is already implemented.

<img src="https://user-images.githubusercontent.com/888679/56280677-fe911900-610a-11e9-8f4a-ce41a6ab8dee.jpeg" width="240" />

I guess more like sharing a URL like this way:

<img src="https://user-images.githubusercontent.com/888679/56281052-eec60480-610b-11e9-9de5-0c35a6b38003.jpeg" width="240" />

Only things I can think of is either:

Sharing your location (screenshot of your map, a link to our website plus a text like "Hey, look at me, I'm at the Critical Mass - connected by Critical Maps")

Or a simple "Tell your friends" button in the settings ("Check out this cool app for Critical Mass plus link to website") ... not a huge fan on this one tbh.

**Comment by lennet** [comment] 2019-04-17 11:17
There is already a share app functionality if you force press on the App icon. Not the most visible feature though

**Comment by mltbnz** [comment] 2019-04-19 08:47
Thats true.
So maybe not reproduce it

**Comment by mltbnz** [comment] 2019-11-02 07:14
Let’s close this since it is not clear what the goal is and there is no clear idea of what to share I think

**Closed** 2019-11-04 09:46 UTC
Labels: new feature
